In [1]:
# Utilisation de Faker
from faker import Faker
import matplotlib.pyplot as plt

fake = Faker()


print(fake.name()) # Exemple : 'Jean Dupont'
print(fake.address()) # Exemple : '10 rue de Paris, 75001 Paris'
print(fake.text()) # Exemple : 'Lorem ipsum dolor sit amet...'

Jennifer Nicholson
1493 Lewis Track Suite 589
East Jeffreyville, OR 52340
Rest small pattern marriage week name pattern girl. Should international though card medical stand. Traditional west computer admit.
Area yet all least. Entire hope size team phone.

In [2]:
from datasets import load_dataset

#dataset = load_dataset("thesofakillers/jigsaw-toxic-comment-classification-challenge")

# or load the separate splits if the dataset has train/validation/test splits
train_dataset = load_dataset("thesofakillers/jigsaw-toxic-comment-classification-challenge", split="train")
#valid_dataset = load_dataset("thesofakillers/jigsaw-toxic-comment-classification-challenge", split="validation")
#test_dataset  = load_dataset("thesofakillers/jigsaw-toxic-comment-classification-challenge", split="test")

c:\Users\xadee\OneDrive\Bureau\ESIGELEC\3A\Deploiement de solution IA\Projet1\API_Digital_Social_Score\.env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
from faker import Faker
import pandas as pd
 
# Initialize Faker
fake = Faker()
 
# Add a new column with fake names
df['fake_name'] = [fake.name() for _ in range(len(df))]
 
# Add another column with fake emails (optional)
df['fake_email'] = [fake.email() for _ in range(len(df))]
 
df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,fake_name,fake_email
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,Amber Kennedy,jacksonkathryn@example.net
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,Jon Harris,roachalex@example.net
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,Laura Jackson DVM,katiesanders@example.org
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,Christopher Jones,qvargas@example.net
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,Joseph Wong,james25@example.net
...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,Sarah Rogers,christopherrios@example.net
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,Mark Hernandez,kathymack@example.com
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,Carl Navarro,ubright@example.org
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,Michael Phillips,ilewis@example.com
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,Chelsea Mullins,kayla41@example.com

In [3]:
# Afficher les premier lignes
import pandas as pd
df = pd.DataFrame(train_dataset)
df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0

In [5]:
from faker import Faker
import pandas as pd
 
# Initialize Faker
fake = Faker()
 
# Add a new column with fake names
df['fake_name'] = [fake.name() for _ in range(len(df))]
 
# Add another column with fake emails (optional)
df['fake_email'] = [fake.email() for _ in range(len(df))]
 
df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,fake_name,fake_email
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,Michelle James,barbara21@example.com
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,Trevor Hernandez,edwardgardner@example.com
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,Elizabeth Reynolds,nwarren@example.com
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,Christopher Alvarado,nduke@example.org
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,Jessica Hunt,stephanie04@example.com
...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,Tyler Blankenship,qdelacruz@example.net
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,Randy Munoz,david98@example.net
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,William Sanchez,sharonadams@example.org
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,David Anderson,jacksondonna@example.net
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,Carlos Reyes,barbara17@example.net

In [18]:
# python -m spacy download en_core_web_sm"

import spacy
import re
import pandas as pd
from tqdm import tqdm

# Charger spaCy pour l'anglais (une seule fois)
nlp = spacy.load("en_core_web_sm")

# Patterns regex pour détecter les données personnelles
EMAIL_PATTERN = re.compile(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b')
PHONE_PATTERN = re.compile(r'\b(?:\+?1[-.\s]?)?\(?[0-9]{3}\)?[-.\s]?[0-9]{3}[-.\s]?[0-9]{4}\b')

def detect_personal_data_rgpd(text):
    """
    Détecte toutes les données personnelles pour la conformité RGPD
    """
    if not text or pd.isna(text):
        return {
            'has_personal_data': False,
            'names': [],
            'emails': [],
            'phones': [],
            'addresses': []
        }
    
    text_str = str(text)
    
    # 1. EMAILS
    emails = EMAIL_PATTERN.findall(text_str)
    
    # 2. TÉLÉPHONES  
    phones = PHONE_PATTERN.findall(text_str)
    
    # 3. NOMS avec spaCy NER
    doc = nlp(text_str)
    names = []
    for ent in doc.ents:
        if ent.label_ == 'PERSON':
            names.append(ent.text)
    
    return {
        'has_personal_data': bool(names or emails or phones),
        'names': names,
        'emails': emails,
        'phones': phones,
    }

def anonymize_text_rgpd(text, detection_result):
    """
    Anonymise automatiquement le texte pour la conformité RGPD
    """
    if not detection_result['has_personal_data']:
        return text
    
    anonymized_text = str(text)
    
    # Anonymiser dans l'ordre : emails, téléphones, adresses, noms
    for email in detection_result['emails']:
        anonymized_text = anonymized_text.replace(email, "[EMAIL]")
    
    for phone in detection_result['phones']:
        anonymized_text = anonymized_text.replace(phone, "[PHONE]")
    
    for name in detection_result['names']:
        anonymized_text = anonymized_text.replace(name, "[NAME]")
    
    return anonymized_text

In [22]:
# CRÉATION DU DATASET ANONYMISÉ (df_anonymized)
print("ANONYMISATION DU DATASET")
print("=" * 30)

# Travailler avec 10 000 données
max_to_anonymize = 10000

# Taille réelle à traiter
actual_size = min(max_to_anonymize, len(df))

print(f"PARAMETRES D'ANONYMISATION:")
print(f"Dataset total: {len(df):,} commentaires")
print(f"A anonymiser: {actual_size:,} commentaires")

# Créer une copie du DataFrame pour l'anonymisation
df_anonymized = df.copy()

# Statistiques de traitement
comments_with_personal_data = 0
total_anonymizations = 0

print(f"\nAnonymisation en cours...")

# Traiter les commentaires avec barre de progression
for i in tqdm(range(actual_size), desc="Anonymisation RGPD"):
    original_comment = df['comment_text'].iloc[i]
    
    # Détecter les données personnelles
    detection = detect_personal_data_rgpd(original_comment)
    
    # Si des données personnelles sont trouvées, anonymiser
    if detection['has_personal_data']:
        comments_with_personal_data += 1
        
        # Compter le nombre total d'éléments à anonymiser
        num_elements = (len(detection['names']) + len(detection['emails']) + len(detection['phones']))
        total_anonymizations += num_elements
        
        # Anonymiser le texte
        anonymized_comment = anonymize_text_rgpd(original_comment, detection)
        
        # Remplacer dans le DataFrame anonymisé
        df_anonymized.loc[i, 'comment_text'] = anonymized_comment

print(f"\nANONYMISATION TERMINEE!")
print(f"STATISTIQUES FINALES:")
print(f"Total commentaires traités: {actual_size:,}")
print(f"Commentaires anonymisés: {comments_with_personal_data:,}")
print(f"Pourcentage de commentaires affectés: {comments_with_personal_data/actual_size*100:.2f}%")
print(f"Total d'éléments anonymisés: {total_anonymizations:,}")

# Sauvegarder le dataset anonymisé
anonymized_filename = "dataset_anonymized_rgpd_10k.csv"
df_anonymized.to_csv(anonymized_filename, index=False)
print(f"\nDataset anonymisé sauvegardé: {anonymized_filename}")

print(f"\nDATASET ANONYMISE PRET:")
print(f"Variable: df_anonymized")
print(f"Taille: {len(df_anonymized):,} commentaires")
print(f"Conformité RGPD: Assurée")
print(f"Prêt pour le nettoyage de données")

ANONYMISATION DU DATASET
==============================
PARAMETRES D'ANONYMISATION:
Dataset total: 159,571 commentaires
A anonymiser: 10,000 commentaires

Anonymisation en cours...

Anonymisation RGPD: 100%|██████████| 10000/10000 [02:34<00:00, 64.73it/s]

ANONYMISATION TERMINEE!
STATISTIQUES FINALES:
Total commentaires traités: 10,000
Commentaires anonymisés: 3,246
Pourcentage de commentaires affectés: 32.46%
Total d'éléments anonymisés: 7,593

Dataset anonymisé sauvegardé: dataset_anonymized_rgpd_10k.csv

DATASET ANONYMISE PRET:
Variable: df_anonymized
Taille: 159,571 commentaires
Conformité RGPD: Assurée
Prêt pour le nettoyage de données

Dataset anonymisé sauvegardé: dataset_anonymized_rgpd_10k.csv

DATASET ANONYMISE PRET:
Variable: df_anonymized
Taille: 159,571 commentaires
Conformité RGPD: Assurée
Prêt pour le nettoyage de données

In [ ]:
# ÉTAPE 1: Configuration du nettoyage de données
import re
import string
import pandas as pd
from tqdm import tqdm

def clean_text(text):
    """
    Fonction complète de nettoyage de texte pour le NLP
    """
    if not text or pd.isna(text):
        return ""
    
    # Convertir en string au cas où
    text = str(text)
    
    # 1. CASSE : Convertir en minuscules
    text = text.lower()
    
    # 2. EMOJIS : Supprimer les emojis (patterns Unicode)
    emoji_pattern = re.compile("["
                              u"\U0001F600-\U0001F64F"  # emoticons
                              u"\U0001F300-\U0001F5FF"  # symboles & pictogrammes
                              u"\U0001F680-\U0001F6FF"  # transport & cartes
                              u"\U0001F1E0-\U0001F1FF"  # drapeaux
                              u"\U00002500-\U00002BEF"  # caractères chinois
                              u"\U00002702-\U000027B0"
                              u"\U00002702-\U000027B0"
                              u"\U000024C2-\U0001F251"
                              u"\U0001f926-\U0001f937"
                              u"\U00010000-\U0010ffff"
                              u"\u2640-\u2642"
                              u"\u2600-\u2B55"
                              u"\u200d"
                              u"\u23cf"
                              u"\u23e9"
                              u"\u231a"
                              u"\ufe0f"  # dingbats
                              u"\u3030"
                              "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)
    
    # 3. CARACTÈRES SPÉCIAUX : Supprimer les caractères non-ASCII
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    
    # 4. URLs : Supprimer les URLs
    text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', ' ', text)
    text = re.sub(r'www\.(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', ' ', text)
    
    # 5. MENTIONS : Supprimer les @mentions
    text = re.sub(r'@\w+', ' ', text)
    
    # 6. HASHTAGS : Supprimer les #hashtags
    text = re.sub(r'#\w+', ' ', text)
    
    # 7. CHIFFRES : Supprimer les chiffres isolés
    text = re.sub(r'\b\d+\b', ' ', text)
    
    # 8. PONCTUATION : Supprimer la ponctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # 9. ESPACES : Normaliser les espaces multiples
    text = re.sub(r'\s+', ' ', text)
    
    # 10. TRIM : Supprimer les espaces en début/fin
    text = text.strip()
    
    return text

In [25]:
# ÉTAPE 3: Application du nettoyage au dataset anonymisé
print("NETTOYAGE DU DATASET ANONYMISE")
print("=" * 35)

# Vérifier que df_anonymized existe
if 'df_anonymized' not in locals():
    print("df_anonymized n'existe pas encore!")
else:
    # Travailler seulement sur les 10 000 données anonymisées
    max_to_clean = 10000
    actual_size_to_clean = min(max_to_clean, len(df_anonymized))
    
    # Créer une copie du dataset anonymisé pour le nettoyage (seulement les 10k)
    df_cleaned = df_anonymized.head(actual_size_to_clean).copy()
    
    # Statistiques de nettoyage
    total_comments = len(df_cleaned)
    original_total_words = 0
    cleaned_total_words = 0
    empty_after_cleaning = 0
    
    print(f"Nettoyage de {total_comments:,} commentaires anonymisés...")
    
    # Appliquer le nettoyage avec barre de progression
    for i in tqdm(range(total_comments), desc="Nettoyage des commentaires"):
        original_comment = df_cleaned['comment_text'].iloc[i]
        
        if original_comment and not pd.isna(original_comment):
            # Compter les mots avant nettoyage
            original_total_words += len(str(original_comment).split())
            
            # Appliquer le nettoyage standard
            cleaned_comment = clean_text(original_comment)
            
            # Remplacer dans le DataFrame
            df_cleaned.loc[i, 'comment_text'] = cleaned_comment
            
            # Compter les mots après nettoyage
            if cleaned_comment:
                cleaned_total_words += len(cleaned_comment.split())
            else:
                empty_after_cleaning += 1
    
    print(f"\nNETTOYAGE TERMINE!")
    print(f"STATISTIQUES DU NETTOYAGE:")
    print(f"Total commentaires traités: {total_comments:,}")
    print(f"Mots avant nettoyage: {original_total_words:,}")
    print(f"Mots après nettoyage: {cleaned_total_words:,}")
    if original_total_words > 0:
        print(f"Réduction: {((original_total_words - cleaned_total_words) / original_total_words * 100):.1f}%")
    print(f"Commentaires vides après nettoyage: {empty_after_cleaning}")
    
    # Supprimer les commentaires vides
    df_cleaned = df_cleaned[df_cleaned['comment_text'].str.len() > 0]
    print(f"Commentaires conservés: {len(df_cleaned):,}")
    
    # Sauvegarder le dataset nettoyé
    cleaned_filename = "dataset_cleaned_and_anonymized_10k.csv"
    df_cleaned.to_csv(cleaned_filename, index=False)
    print(f"\nDataset nettoyé sauvegardé: {cleaned_filename}")
    
    print(f"\nDATASET FINAL PRET:")
    print(f"Variable: df_cleaned")
    print(f"Anonymisé: OUI (RGPD conforme)")
    print(f"Nettoyé: OUI (prêt pour ML)")
    print(f"Taille: {len(df_cleaned):,} commentaires")
    print(f"Prêt pour l'entraînement SVM")

NETTOYAGE DU DATASET ANONYMISE
===================================
Nettoyage de 10,000 commentaires anonymisés...

Nettoyage des commentaires: 100%|██████████| 10000/10000 [00:02<00:00, 4066.44it/s]

NETTOYAGE TERMINE!
STATISTIQUES DU NETTOYAGE:
Total commentaires traités: 10,000
Mots avant nettoyage: 680,323
Mots après nettoyage: 662,538
Réduction: 2.6%
Commentaires vides après nettoyage: 3
Commentaires conservés: 9,997

Dataset nettoyé sauvegardé: dataset_cleaned_and_anonymized_10k.csv

DATASET FINAL PRET:
Variable: df_cleaned
Anonymisé: OUI (RGPD conforme)
Nettoyé: OUI (prêt pour ML)
Taille: 9,997 commentaires
Prêt pour l'entraînement SVM

In [26]:
# ÉTAPE 4: Analyse de la qualité du nettoyage
print("ANALYSE DE LA QUALITE DU NETTOYAGE")
print("=" * 40)

# Vérifier que les DataFrames existent
if 'df_anonymized' not in locals() or 'df_cleaned' not in locals():
    print("Veuillez d'abord exécuter les étapes d'anonymisation et de nettoyage.")
else:
    # Comparaison avant/après nettoyage
    print("COMPARAISON AVANT/APRES NETTOYAGE:")
    
    # Afficher quelques exemples de transformation
    examples_to_show = 5
    examples_count = 0
    
    for i in range(min(100, len(df_anonymized), len(df_cleaned))):
        original = df_anonymized['comment_text'].iloc[i]
        cleaned = df_cleaned['comment_text'].iloc[i]
        
        # Montrer seulement les exemples où il y a une différence significative
        if (original and cleaned and 
            str(original) != str(cleaned) and 
            len(str(original)) > 20 and 
            examples_count < examples_to_show):
            
            examples_count += 1
            print(f"\nExemple {examples_count}:")
            print(f"  AVANT: {str(original)[:120]}...")
            print(f"  APRÈS: {str(cleaned)[:120]}...")
            
            # Analyse des transformations
            orig_words = len(str(original).split())
            clean_words = len(str(cleaned).split())
            reduction = ((orig_words - clean_words) / orig_words * 100) if orig_words > 0 else 0
            
            print(f"  STATS: {orig_words} -> {clean_words} mots (-{reduction:.1f}%)")
    
    # Analyse statistique globale
    print(f"\nANALYSE STATISTIQUE GLOBALE:")
    
    # Longueur moyenne des commentaires
    if len(df_cleaned) > 0:
        original_lengths = [len(str(text).split()) for text in df_anonymized['comment_text'].head(1000) if text]
        cleaned_lengths = [len(str(text).split()) for text in df_cleaned['comment_text'].head(1000) if text]
        
        avg_original = sum(original_lengths) / len(original_lengths) if original_lengths else 0
        avg_cleaned = sum(cleaned_lengths) / len(cleaned_lengths) if cleaned_lengths else 0
        
        print(f"Longueur moyenne avant: {avg_original:.1f} mots")
        print(f"Longueur moyenne après: {avg_cleaned:.1f} mots")
        if avg_original > 0:
            print(f"Réduction moyenne: {((avg_original - avg_cleaned) / avg_original * 100):.1f}%")
    
    # Distribution des labels dans le dataset nettoyé
    if 'toxic' in df_cleaned.columns:
        toxic_distribution = df_cleaned['toxic'].value_counts()
        print(f"\nDISTRIBUTION DES LABELS (dataset nettoyé):")
        print(f"Non-toxiques: {toxic_distribution.get(0, 0):,} ({toxic_distribution.get(0, 0)/len(df_cleaned)*100:.1f}%)")
        print(f"Toxiques: {toxic_distribution.get(1, 0):,} ({toxic_distribution.get(1, 0)/len(df_cleaned)*100:.1f}%)")
    
    if 'insult' in df_cleaned.columns:
        insult_distribution = df_cleaned['insult'].value_counts()
        print(f"Non-insultants: {insult_distribution.get(0, 0):,} ({insult_distribution.get(0, 0)/len(df_cleaned)*100:.1f}%)")
        print(f"Insultants: {insult_distribution.get(1, 0):,} ({insult_distribution.get(1, 0)/len(df_cleaned)*100:.1f}%)")
    
    # Vérification de la qualité
    print(f"\nVERIFICATION DE QUALITE:")
    very_short_comments = len(df_cleaned[df_cleaned['comment_text'].str.len() < 10])
    print(f"Commentaires très courts (< 10 char): {very_short_comments}")
    print(f"Pourcentage de commentaires courts: {very_short_comments/len(df_cleaned)*100:.2f}%")
    
    print(f"\nDATASET FINAL PRET:")
    print(f"{len(df_cleaned):,} commentaires nettoyés et anonymisés")
    print(f"Conformité RGPD: Assurée")
    print(f"Nettoyage: Optimisé pour ML")
    print(f"Prêt pour l'entraînement SVM")
    
    # Aperçu du dataset final
    print(f"\nAPERCU DU DATASET FINAL:")
    display_columns = ['comment_text', 'toxic']
    if 'insult' in df_cleaned.columns:
        display_columns.append('insult')
    
    print(df_cleaned[display_columns].head(3))
    
    print(f"\nFICHIERS CREES:")
    print(f"dataset_anonymized_rgpd_10k.csv (dataset anonymisé)")
    print(f"dataset_cleaned_and_anonymized_10k.csv (dataset final)")
    print(f"Variables disponibles: df_anonymized, df_cleaned")

ANALYSE DE LA QUALITE DU NETTOYAGE
========================================
COMPARAISON AVANT/APRES NETTOYAGE:

Exemple 1:
  AVANT: Explanation
Why the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just clo...
  APRÈS: explanation why the edits made under my username hardcore metallica fan were reverted they werent vandalisms just closur...
  STATS: 43 -> 43 mots (-0.0%)

Exemple 2:
  AVANT: D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)...
  APRÈS: daww he matches this background colour im seemingly stuck with thanks talk january utc...
  STATS: 17 -> 14 mots (-17.6%)

Exemple 3:
  AVANT: Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talk...
  APRÈS: hey man im really not trying to edit war its just that this guy is constantly removing relevant information and talking ...
  STATS: 42 -> 42 mots (-0.0%)

Exemple 4:
  AVANT: "
More
I can't make any real suggestions on improvement - I wondered if the section statistics should be later on, or a ...
  APRÈS: more i cant make any real suggestions on improvement i wondered if the section statistics should be later on or a subsec...
  STATS: 113 -> 109 mots (-3.5%)

Exemple 5:
  AVANT: You, sir, are my hero. Any chance you remember what page that's on?...
  APRÈS: you sir are my hero any chance you remember what page thats on...
  STATS: 13 -> 13 mots (-0.0%)

ANALYSE STATISTIQUE GLOBALE:
Longueur moyenne avant: 69.1 mots
Longueur moyenne après: 66.8 mots
Réduction moyenne: 3.4%

DISTRIBUTION DES LABELS (dataset nettoyé):
Non-toxiques: 9,026 (90.3%)
Toxiques: 971 (9.7%)
Non-insultants: 9,503 (95.1%)
Insultants: 494 (4.9%)

VERIFICATION DE QUALITE:
Commentaires très courts (< 10 char): 27
Pourcentage de commentaires courts: 0.27%

DATASET FINAL PRET:
9,997 commentaires nettoyés et anonymisés
Conformité RGPD: Assurée
Nettoyage: Optimisé pour ML
Prêt pour l'entraînement SVM

APERCU DU DATASET FINAL:
                                        comment_text  toxic  insult
0  explanation why the edits made under my userna...      0       0
1  daww he matches this background colour im seem...      0       0
2  hey man im really not trying to edit war its j...      0       0

FICHIERS CREES:
dataset_anonymized_rgpd_10k.csv (dataset anonymisé)
dataset_cleaned_and_anonymized_10k.csv (dataset final)
Variables disponibles: df_anonymized, df_cleaned